-- startsWithCaseInsensitiveUTF8 and endsWithCaseInsensitiveUTF8 must match code points like positionCaseInsensitiveUTF8,
-- also when the match and the needle differ in byte length. Each function prints const/const, column/const, column/column, const/column.

SELECT 'startsWith';
WITH 'ß' AS h, 'ẞ' AS n SELECT 'sharp s to capital', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'ẞ' AS h, 'ß' AS n SELECT 'capital to sharp s', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'xß' AS h, 'ẞ' AS n SELECT 'capital at end', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'ßx' AS h, 'ẞ' AS n SELECT 'capital at start', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'ⱥ' AS h, 'Ⱥ' AS n SELECT 'A-bar to a-bar', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'Ⱥ' AS h, 'ⱥ' AS n SELECT 'a-bar to A-bar', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'xxⱥ' AS h, 'Ⱥ' AS n SELECT 'a-bar at end', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'Ⱥxx' AS h, 'ⱥ' AS n SELECT 'a-bar at start', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'STRAẞE' AS h, 'straße' AS n SELECT 'STRASSE', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'ß' AS h, 'ss' AS n SELECT 'sharp s vs ss', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH concat(char(0xE2, 0x84, 0xAA), 'x', char(0xE2, 0x84, 0xAA)) AS h, 'k' AS n SELECT 'kelvin vs k', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'kxk' AS h, char(0xE2, 0x84, 0xAA) AS n SELECT 'k vs kelvin', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH concat(char(0xE2, 0x84, 0xAA), 'x', char(0xE2, 0x84, 0xAA)) AS h, char(0xE2, 0x84, 0xAA) AS n SELECT 'kelvin to kelvin', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'Hello World' AS h, 'hELLO' AS n SELECT 'ascii prefix', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'Hello World' AS h, 'wORLD' AS n SELECT 'ascii suffix', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'abc' AS h, '' AS n SELECT 'empty needle', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH '' AS h, '' AS n SELECT 'both empty', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH '' AS h, 'a' AS n SELECT 'empty haystack', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;
WITH 'ab' AS h, 'abc' AS n SELECT 'needle longer', startsWithCaseInsensitiveUTF8(h, n), startsWithCaseInsensitiveUTF8(materialize(h), n), startsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), startsWithCaseInsensitiveUTF8(h, materialize(n)), positionCaseInsensitiveUTF8(h, n) = 1;

SELECT 'endsWith';
WITH 'ß' AS h, 'ẞ' AS n SELECT 'sharp s to capital', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'ẞ' AS h, 'ß' AS n SELECT 'capital to sharp s', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'xß' AS h, 'ẞ' AS n SELECT 'capital at end', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'ßx' AS h, 'ẞ' AS n SELECT 'capital at start', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'ⱥ' AS h, 'Ⱥ' AS n SELECT 'A-bar to a-bar', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'Ⱥ' AS h, 'ⱥ' AS n SELECT 'a-bar to A-bar', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'xxⱥ' AS h, 'Ⱥ' AS n SELECT 'a-bar at end', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'Ⱥxx' AS h, 'ⱥ' AS n SELECT 'a-bar at start', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'STRAẞE' AS h, 'straße' AS n SELECT 'STRASSE', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'ß' AS h, 'ss' AS n SELECT 'sharp s vs ss', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH concat(char(0xE2, 0x84, 0xAA), 'x', char(0xE2, 0x84, 0xAA)) AS h, 'k' AS n SELECT 'kelvin vs k', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'kxk' AS h, char(0xE2, 0x84, 0xAA) AS n SELECT 'k vs kelvin', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH concat(char(0xE2, 0x84, 0xAA), 'x', char(0xE2, 0x84, 0xAA)) AS h, char(0xE2, 0x84, 0xAA) AS n SELECT 'kelvin to kelvin', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'Hello World' AS h, 'hELLO' AS n SELECT 'ascii prefix', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'Hello World' AS h, 'wORLD' AS n SELECT 'ascii suffix', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'abc' AS h, '' AS n SELECT 'empty needle', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH '' AS h, '' AS n SELECT 'both empty', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH '' AS h, 'a' AS n SELECT 'empty haystack', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));
WITH 'ab' AS h, 'abc' AS n SELECT 'needle longer', endsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(materialize(h), n), endsWithCaseInsensitiveUTF8(materialize(h), materialize(n)), endsWithCaseInsensitiveUTF8(h, materialize(n));

SELECT 'rows of different lengths';
SELECT h, n, startsWithCaseInsensitiveUTF8(h, n), endsWithCaseInsensitiveUTF8(h, n) FROM values('h String, n String', ('ß', 'ẞ'), ('xß', 'ẞ'), ('ẞx', 'ß'), ('Ⱥ', 'ⱥ'), ('xⱥ', 'Ⱥ'), ('abc', ''), ('', 'a'), ('AbC', 'abc'));
SELECT h, startsWithCaseInsensitiveUTF8(h, 'ẞ'), endsWithCaseInsensitiveUTF8(h, 'ẞ') FROM values('h String', ('ß'), ('xß'), ('ßx'), (''), ('ẞ'));
